import React, { useState, useMemo } from 'react';
import { 
  Plus, 
  Trash2, 
  Download, 
  Copy, 
  ClipboardCheck,
  Calendar,
  Clock,
  User,
  FileText,
  Eye,
  EyeOff,
  RefreshCw
} from 'lucide-react';
import jsPDF from 'jspdf';

/**
 * MeetingAgendaGenerator Component
 * 
 * A professional meeting agenda generator with PDF export and copy functionality.
 * Features:
 * - Meeting details input
 * - Dynamic attendees list
 * - Dynamic agenda points
 * - Live preview
 * - PDF download
 * - Copy to clipboard
 * - Clean professional layout
 */

// ==================== TypeScript Interfaces ====================

export interface Attendee {
  id: string;
  name: string;
  role: string;
}

export interface AgendaPoint {
  id: string;
  title: string;
  duration: string;
  presenter: string;
}

export interface MeetingAgenda {
  title: string;
  companyName: string;
  date: string;
  time: string;
  duration: string;
  organizerName: string;
  attendees: Attendee[];
  agendaPoints: AgendaPoint[];
  notes: string;
}

// ==================== Helper Functions ====================

const createEmptyAttendee = (): Attendee => ({
  id: crypto.randomUUID(),
  name: '',
  role: ''
});

const createEmptyAgendaPoint = (): AgendaPoint => ({
  id: crypto.randomUUID(),
  title: '',
  duration: '15 min',
  presenter: ''
});

// Generate formatted agenda document
const generateAgendaDocument = (agenda: MeetingAgenda): string => {
  const { title, companyName, date, time, duration, organizerName, attendees, agendaPoints, notes } = agenda;
  
  const formattedDate = new Date(date).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const agendaDocument = `
╔══════════════════════════════════════════════════════════════════════╗
║                           MEETING AGENDA                             ║
╚══════════════════════════════════════════════════════════════════════╝

📌 MEETING DETAILS
──────────────────────────────────────────────────────────────────────
📝 Title: ${title || '[Meeting Title]'}
🏢 Company: ${companyName || '[Company Name]'}
📅 Date: ${formattedDate}
⏰ Time: ${time || '[Time]'}
⏱️ Duration: ${duration || '[Duration]'}
👤 Organizer: ${organizerName || '[Organizer Name]'}

📋 ATTENDEES
──────────────────────────────────────────────────────────────────────
${attendees.length > 0 ? attendees.map((a, i) => `${i + 1}. ${a.name || 'TBD'} ${a.role ? `(${a.role})` : ''}`).join('\n') : '• TBD'}

📌 AGENDA
──────────────────────────────────────────────────────────────────────
${agendaPoints.length > 0 ? agendaPoints.map((point, i) => {
  return `${i + 1}. ${point.title || 'TBD'}
   ⏱️ Duration: ${point.duration}
   👤 Presenter: ${point.presenter || 'TBD'}
`;
}).join('\n') : '• No agenda points added'}

📝 NOTES
──────────────────────────────────────────────────────────────────────
${notes || '• No additional notes'}

──────────────────────────────────────────────────────────────────────
Generated by Meeting Agenda Generator
`.trim();

  return agendaDocument;
};

// ==================== Component ====================

const MeetingAgendaGenerator: React.FC = () => {
  // State for meeting details
  const [title, setTitle] = useState<string>('');
  const [companyName, setCompanyName] = useState<string>('');
  const [date, setDate] = useState<string>(new Date().toISOString().split('T')[0]);
  const [time, setTime] = useState<string>('10:00');
  const [duration, setDuration] = useState<string>('60 minutes');
  const [organizerName, setOrganizerName] = useState<string>('');
  const [attendees, setAttendees] = useState<Attendee[]>([createEmptyAttendee()]);
  const [agendaPoints, setAgendaPoints] = useState<AgendaPoint[]>([createEmptyAgendaPoint()]);
  const [notes, setNotes] = useState<string>('');
  const [showPreview, setShowPreview] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  // Build agenda object for preview
  const agendaData: MeetingAgenda = useMemo(() => ({
    title,
    companyName,
    date,
    time,
    duration,
    organizerName,
    attendees,
    agendaPoints,
    notes
  }), [title, companyName, date, time, duration, organizerName, attendees, agendaPoints, notes]);

  // Generate document
  const agendaDoc = useMemo(() => generateAgendaDocument(agendaData), [agendaData]);

  // Add attendee
  const addAttendee = () => {
    setAttendees([...attendees, createEmptyAttendee()]);
  };

  // Remove attendee
  const removeAttendee = (id: string) => {
    if (attendees.length > 1) {
      setAttendees(attendees.filter(a => a.id !== id));
    }
  };

  // Update attendee
  const updateAttendee = (id: string, field: keyof Attendee, value: string) => {
    setAttendees(attendees.map(a => a.id === id ? { ...a, [field]: value } : a));
  };

  // Add agenda point
  const addAgendaPoint = () => {
    setAgendaPoints([...agendaPoints, createEmptyAgendaPoint()]);
  };

  // Remove agenda point
  const removeAgendaPoint = (id: string) => {
    if (agendaPoints.length > 1) {
      setAgendaPoints(agendaPoints.filter(p => p.id !== id));
    }
  };

  // Update agenda point
  const updateAgendaPoint = (id: string, field: keyof AgendaPoint, value: string) => {
    setAgendaPoints(agendaPoints.map(p => p.id === id ? { ...p, [field]: value } : p));
  };

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(agendaDoc);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  // Generate PDF
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('MEETING AGENDA', pageWidth / 2, 20, { align: 'center' });
    
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(20, 25, pageWidth - 20, 25);
    
    let yPos = 35;
    
    // Meeting Details
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('MEETING DETAILS', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const details = [
      ['Title:', title || 'TBD'],
      ['Company:', companyName || 'TBD'],
      ['Date:', new Date(date).toLocaleDateString()],
      ['Time:', time],
      ['Duration:', duration],
      ['Organizer:', organizerName || 'TBD']
    ];
    
    details.forEach(([label, value]) => {
      doc.setFont('helvetica', 'bold');
      doc.text(label, 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 60, yPos);
      yPos += 6;
    });
    
    yPos += 5;
    
    // Attendees
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('ATTENDEES', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    if (attendees.length > 0 && attendees[0].name) {
      attendees.forEach((attendee, index) => {
        doc.text(`${index + 1}. ${attendee.name}${attendee.role ? ` (${attendee.role})` : ''}`, 20, yPos);
        yPos += 5;
      });
    } else {
      doc.text('TBD', 20, yPos);
      yPos += 5;
    }
    
    yPos += 5;
    
    // Agenda Points
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('AGENDA', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    
    if (agendaPoints.length > 0 && agendaPoints[0].title) {
      agendaPoints.forEach((point, index) => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${point.title}`, 20, yPos);
        yPos += 5;
        doc.setFont('helvetica', 'normal');
        doc.text(`   Duration: ${point.duration} | Presenter: ${point.presenter || 'TBD'}`, 20, yPos);
        yPos += 8;
      });
    } else {
      doc.text('No agenda points added', 20, yPos);
      yPos += 5;
    }
    
    yPos += 5;
    
    // Notes
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('NOTES', 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    if (notes) {
      const noteLines = doc.splitTextToSize(notes, pageWidth - 40);
      doc.text(noteLines, 20, yPos);
    } else {
      doc.text('No additional notes', 20, yPos);
    }
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Meeting Agenda Generator', pageWidth / 2, 285, { align: 'center' });
    
    doc.save(`${title || 'meeting-agenda'}.pdf`);
  };

  // Reset form
  const handleReset = () => {
    setTitle('');
    setCompanyName('');
    setDate(new Date().toISOString().split('T')[0]);
    setTime('10:00');
    setDuration('60 minutes');
    setOrganizerName('');
    setAttendees([createEmptyAttendee()]);
    setAgendaPoints([createEmptyAgendaPoint()]);
    setNotes('');
  };

  // Duration options
  const durationOptions = [
    '15 minutes', '30 minutes', '45 minutes', '60 minutes', 
    '90 minutes', '2 hours', '3 hours', 'Half day', 'Full day'
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 py-8 px-4 sm:px-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-500 mb-4">
            <FileText className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-white mb-2">Meeting Agenda Generator</h1>
          <p className="text-gray-400">Create professional meeting agendas instantly</p>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-3 justify-between mb-6 no-print">
          <div className="flex gap-3">
            <button
              onClick={handleReset}
              className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              Reset
            </button>
            <button
              onClick={() => setShowPreview(!showPreview)}
              className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-lg transition-colors"
            >
              {showPreview ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              {showPreview ? 'Hide' : 'Show'} Preview
            </button>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
            >
              {copied ? <ClipboardCheck className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={generatePDF}
              className="flex items-center gap-2 px-4 py-2 bg-cyan-600 hover:bg-cyan-700 text-white rounded-lg transition-colors"
            >
              <Download className="w-4 h-4" />
              Download PDF
            </button>
          </div>
        </div>

        <div className={`grid grid-cols-1 xl:grid-cols-2 gap-8 ${showPreview ? '' : 'max-w-3xl mx-auto'}`}>
          {/* Form Section */}
          <div className="space-y-6">
            {/* Meeting Details */}
            <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl p-6 border border-gray-700/50">
              <h3 className="text-white font-semibold text-lg mb-4 flex items-center gap-2">
                <Calendar className="w-5 h-5 text-cyan-400" />
                Meeting Details
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-2">
                  <label className="block text-gray-400 text-sm mb-1">Meeting Title *</label>
                  <input
                    type="text"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="Weekly Team Standup"
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-1">Company Name</label>
                  <input
                    type="text"
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    placeholder="Acme Corporation"
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-1">Date</label>
                  <input
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-1">Time</label>
                  <input
                    type="time"
                    value={time}
                    onChange={(e) => setTime(e.target.value)}
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
                <div>
                  <label className="block text-gray-400 text-sm mb-1">Duration</label>
                  <select
                    value={duration}
                    onChange={(e) => setDuration(e.target.value)}
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  >
                    {durationOptions.map(opt => (
                      <option key={opt} value={opt}>{opt}</option>
                    ))}
                  </select>
                </div>
                <div className="sm:col-span-2">
                  <label className="block text-gray-400 text-sm mb-1">Organizer Name</label>
                  <input
                    type="text"
                    value={organizerName}
                    onChange={(e) => setOrganizerName(e.target.value)}
                    placeholder="John Doe"
                    className="w-full h-11 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                  />
                </div>
              </div>
            </div>

            {/* Attendees */}
            <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl p-6 border border-gray-700/50">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-white font-semibold text-lg flex items-center gap-2">
                  <User className="w-5 h-5 text-purple-400" />
                  Attendees
                </h3>
                <button
                  onClick={addAttendee}
                  className="flex items-center gap-1 px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm transition-colors"
                >
                  <Plus className="w-4 h-4" /> Add
                </button>
              </div>
              <div className="space-y-3">
                {attendees.map((attendee) => (
                  <div key={attendee.id} className="flex gap-2">
                    <input
                      type="text"
                      value={attendee.name}
                      onChange={(e) => updateAttendee(attendee.id, 'name', e.target.value)}
                      placeholder="Attendee name"
                      className="flex-1 h-10 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                    />
                    <input
                      type="text"
                      value={attendee.role}
                      onChange={(e) => updateAttendee(attendee.id, 'role', e.target.value)}
                      placeholder="Role (e.g., Manager)"
                      className="w-40 h-10 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                    />
                    {attendees.length > 1 && (
                      <button
                        onClick={() => removeAttendee(attendee.id)}
                        className="p-2 text-red-400 hover:text-red-300"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Agenda Points */}
            <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl p-6 border border-gray-700/50">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-white font-semibold text-lg flex items-center gap-2">
                  <Clock className="w-5 h-5 text-amber-400" />
                  Agenda Points
                </h3>
                <button
                  onClick={addAgendaPoint}
                  className="flex items-center gap-1 px-3 py-1.5 bg-green-600 hover:bg-green-700 text-white rounded-lg text-sm transition-colors"
                >
                  <Plus className="w-4 h-4" /> Add
                </button>
              </div>
              <div className="space-y-3">
                {agendaPoints.map((point) => (
                  <div key={point.id} className="bg-gray-700/30 rounded-lg p-3">
                    <div className="flex gap-2 mb-2">
                      <input
                        type="text"
                        value={point.title}
                        onChange={(e) => updateAgendaPoint(point.id, 'title', e.target.value)}
                        placeholder="Agenda topic"
                        className="flex-1 h-10 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                      />
                      {agendaPoints.length > 1 && (
                        <button
                          onClick={() => removeAgendaPoint(point.id)}
                          className="p-2 text-red-400 hover:text-red-300"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                    <div className="flex gap-2">
                      <input
                        type="text"
                        value={point.duration}
                        onChange={(e) => updateAgendaPoint(point.id, 'duration', e.target.value)}
                        placeholder="Duration (e.g., 15 min)"
                        className="flex-1 h-10 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                      />
                      <input
                        type="text"
                        value={point.presenter}
                        onChange={(e) => updateAgendaPoint(point.id, 'presenter', e.target.value)}
                        placeholder="Presenter"
                        className="flex-1 h-10 px-3 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Notes */}
            <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl p-6 border border-gray-700/50">
              <h3 className="text-white font-semibold text-lg mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-green-400" />
                Notes
              </h3>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="Additional notes or preparation items..."
                rows={4}
                className="w-full px-3 py-2 bg-gray-700/50 border border-gray-600 rounded-lg text-white focus:outline-none focus:border-cyan-500 resize-none"
              />
            </div>
          </div>

          {/* Preview Section */}
          {showPreview && (
            <div className="xl:sticky xl:top-8 xl:h-fit">
              <div className="bg-gray-800/50 backdrop-blur-lg rounded-2xl overflow-hidden shadow-2xl">
                <div className="px-6 py-4 bg-gray-700 flex items-center justify-between">
                  <span className="font-semibold text-white">Live Preview</span>
                  <span className="text-sm text-gray-400">Formatted Agenda</span>
                </div>
                <div className="p-6 max-h-[800px] overflow-y-auto bg-gray-800">
                  <pre className="whitespace-pre-wrap text-sm text-gray-300 font-mono leading-relaxed">
                    {agendaDoc}
                  </pre>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default MeetingAgendaGenerator;
